### ISSUE TITLE
AttributeError: Can't pickle local object 'modify_gym_env_render.<locals>.render'

### ISSUE THREAD

**Issue by Semizenbora** [chainer/chainerrl-visualizer#12]
Hey,

When I try to run python main.py from examples, I get the following error. How may I solve this?
Thanks in advance.

C:\chainerrl-visualizer\examples\a3c_breakout>python main.py
C:\Anaconda3\envs\tens\lib\site-packages\gym\logger.py:30: UserWarning: [33mWARN: <class 'chainerrl.wrappers.atari_wrappers.FrameStack'> doesn't implement 'reset' method, but it implements deprecated '_reset' method.[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    launch_visualizer(agent, env, ACTION_MEANINGS, raw_image_input=True)
  File "c:\chainerrl-visualizer\chainerrl_visualizer\launcher.py", line 50, in launch_visualizer
    server_process.start()
  File "C:\Anaconda3\envs\tens\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda3\envs\tens\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Anaconda3\envs\tens\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda3\envs\tens\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Anaconda3\envs\tens\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'modify_gym_env_render.<locals>.render'

(tens) C:\chainerrl-visualizer\examples\a3c_breakout> Directory `C:\chainerrl-visualizer\examples\a3c_breakout\log_space` is already exists. Do you use this directory for log output? (y/n) y
'y' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sykwer** [comment]
Sorry, ChainerRL Visualizer is not tested on Windows. Multiprocessing in python sometimes does not work well on Windows.

**Comment by hindamosh** [comment]
So any way to work around it to solve this issue , I have the same problem with my selenium script
